### ISSUE TITLE
trustAllServers by default

### ISSUE THREAD

**Issue by karoldrazek** [malaskowski/aet-docker#16]
Would it be possible to have 'trustAllServers' clause added by default to browsermob?
It happens often that some problematic SSL certificate causes issues collecting results.

**Comment by Skejven** [comment]
It doesn't look that the latest version of BMP supports global setting for trusting all servers:
https://github.com/lightbody/browsermob-proxy/blob/browsermob-proxy-2.1.4/browsermob-rest/src/main/java/net/lightbody/bmp/proxy/guice/ConfigModule.java#L18

That's all I can do on the Docker image level: 
https://github.com/Skejven/aet-docker/blob/master/browsermob/Dockerfile#L45

Do you know any other way to set this globally for BMP?
In the [lightbody Rest API docs](https://github.com/lightbody/browsermob-proxy#rest-api) I found param `trustAllServers` but it looks that is should be sent with each request for creating proxy. That part is done in the AET core (somewhere in the [proxy OSGi wrapper](https://github.com/Cognifide/aet/tree/master/osgi-dependencies/proxy) module). But for creating proxies, AET uses that lib: https://github.com/Cognifide/aet/blob/master/osgi-dependencies/proxy/pom.xml#L81

I'am not sure if that have the option, unfortunately it looks that this project is not active any more: https://github.com/detro/browsermob-proxy-client
